name: Terraform Module Releaser
description: Automate versioning, releases, and documentation for Terraform modules in GitHub monorepos.
author: TechPivot
branding:
  icon: package
  color: purple

inputs:
  major-keywords:
    description: Keywords in commit messages that indicate a major release.
    required: true
    default: major change,breaking change
  minor-keywords:
    description: Keywords in commit messages that indicate a minor release.
    required: true
    default: feat,feature
  patch-keywords:
    description: >
      Keywords in commit messages that indicate a patch release. By default, everything will be a patch
      release if major or minor keywords are not found.
    required: true
    default: fix,chore,docs
  default-first-tag:
    description: Specifies the default tag version. (Should be in format v#.#.#)
    required: true
    default: v1.0.0
  github_token:
    description: Use this if you wish to use a different GitHub token than the one provided by the workflow.
    required: true
    default: ${{ github.token }}default
  terraform-docs-version:
    description: >
      Specifies the terraform-docs version used to generate documentation for the wiki.

      See: https://github.com/terraform-docs/terraform-docs/releases
    required: true
    default: v0.19.0
  delete-legacy-tags:
    description: >
      Specifies a boolean that determines whether tags from Terraform modules that have been deleted
      should be automatically removed. By default this is true as the purpose of the repository is to keep
      releases/tags clean. When removing a module, this will ensure the tags/releases are automatically
      cleaned.
    required: true
    default: "true"
  disable-wiki:
    description: >
      Whether to disable wiki generation for Terraform modules.
      By default, this is set to false. Set to true to prevent wiki documentation from being generated.
    required: true
    default: "false"
  wiki-sidebar-changelog-max:
    description: >
      An integer that specifies how many changelog entries are displayed in the sidebar per module.
      Adjust this value to control the visibility of changelog entries in the module sidebar.
    required: true
    default: "5"

runs:
  using: node20
  main: dist/index.js
