version: ""

header-from: main.tf
footer-from: ""

recursive:
  enabled: false
  path: modules
  include-main: true

sections:
  #hide: ["providers", "inputs"]
  show: []

formatter: "toml"

sort:
  enabled: true
  by: type
