name: Test

on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request.
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  Tests:
    runs-on: ubuntu-latest
    name: TypeScript Tests
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        run: npm ci --no-fund

      - name: Run Tests Typescript
        run: npm run test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Note: SonarQube requires the results from tests to get the coverage report
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@22918119ff8e1ca75a623e15c8296b6ea4fbe28f # v8.2.1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
